name: Democracy
version: '${project.version}'
main: dansplugins.democracy.Democracy
api-version: 1.13
depend: [MedievalFactions]

commands:
  democracy:
  d:

permissions:
  d.help:
    default: true
