name: Democracy
version: '${project.version}'
main: dansplugins.democracy.Democracy
api-version: 1.13
depend: [MedievalFactions]

commands:
  democracy:
  d:

permissions:
  d.help:
    default: true
  d.info:
    default: true
  d.vote:
    default: true
  d.run:
    default: true
  d.dropout:
    default: true
  d.start:
    default: true